module.exports = [
  {
    slug: "wedding-vows",
    title: "The Wedding Vows Workbook",
    description: "A guided writing experience for the promise you'll speak out loud.",
    status: "available",
    href: "/workbook/",
  },
  {
    slug: "wedding-toast",
    title: "The Wedding Toast Workbook",
    description: "For the friend raising a glass and hoping to get it right.",
    status: "coming-soon",
  },
  {
    slug: "best-man-speech",
    title: "The Best Man Speech Workbook",
    description: "Structure, story, and just enough humor — without the panic.",
    status: "coming-soon",
  },
  {
    slug: "maid-of-honor-speech",
    title: "The Maid of Honor Speech Workbook",
    description: "Help finding the words for someone you've known forever.",
    status: "coming-soon",
  },
  {
    slug: "father-of-the-bride-speech",
    title: "The Father of the Bride Speech Workbook",
    description: "For the speech that's been forming in your head for years.",
    status: "coming-soon",
  },
  {
    slug: "mother-of-the-groom-speech",
    title: "The Mother of the Groom Speech Workbook",
    description: "A guide for speaking with warmth, without losing your composure.",
    status: "coming-soon",
  },
  {
    slug: "retirement-speech",
    title: "The Retirement Speech Workbook",
    description: "Honoring decades of work in a few unforgettable minutes.",
    status: "coming-soon",
  },
  {
    slug: "graduation-speech",
    title: "The Graduation Speech Workbook",
    description: "For the milestone that deserves more than a few notecards.",
    status: "coming-soon",
  },
  {
    slug: "proposal",
    title: "The Proposal Workbook",
    description: "Finding the words for the question that starts everything.",
    status: "coming-soon",
  },
  {
    slug: "anniversary-letter",
    title: "The Anniversary Letter Workbook",
    description: "A yearly tradition of writing down what you'd otherwise just feel.",
    status: "coming-soon",
  },
  {
    slug: "eulogy",
    title: "The Eulogy Guide",
    description: "Gentle, practical help for one of the hardest things you'll ever write.",
    status: "coming-soon",
  },
  {
    slug: "letter-to-my-child",
    title: "The Letter to My Child Workbook",
    description: "For the things you want them to read someday, in your own words.",
    status: "coming-soon",
  },
];
